name: cnn
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - jupyterlab
  - pillow
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - tensorflow=2.12.0
  - keras=2.12.0